### ISSUE TITLE
Criação dos protótipos de tela para o site.

### ISSUE THREAD

**Issue by TiagoCCDB** [devfest-ufrn/DogLove#4]

**Comment by atilacaetano** [comment]
![interface 2_dl](https://user-images.githubusercontent.com/16885064/30711574-906478c6-9edf-11e7-95bd-f4712e4eb2ce.jpg)
![interface 1_dl](https://user-images.githubusercontent.com/16885064/30711575-90649b8a-9edf-11e7-84b6-f922bfe2a4bc.jpg)
![prototipo mobile_dl](https://user-images.githubusercontent.com/16885064/30711573-9062533e-9edf-11e7-856f-0dd0528d733c.jpg)

**Comment by LuisandradeA** [comment]
![whatsapp image 2017-09-21 at 14 40 01](https://user-images.githubusercontent.com/15342686/30712088-1ff63870-9ee1-11e7-9663-8d7e1613d198.jpeg)
